[package]
name = "rstd"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.0", features = ["full"] }
sqlx = { version = "0.8.2", features = ["runtime-tokio", "sqlite"] }
clap = { version = "4.5.20", features = ["derive"] }
dotenv = "0.15.0"
